# Google Cloud Build configuration for HKT Platform
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hkt-platform:$SHORT_SHA', '.']
    timeout: '600s'
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hkt-platform:$SHORT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'hkt-platform'
      - '--image=gcr.io/$PROJECT_ID/hkt-platform:$SHORT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-env-vars=NODE_ENV=production'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=300'
      - '--max-instances=10'
      - '--min-instances=0'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

# Build timeout
timeout: '1200s'

# Substitutions
substitutions:
  _SERVICE_NAME: hkt-platform
  _REGION: us-central1